#+title: Emacs Config

My Emacs config, I guess. Making it literate cuz it's probably gonna become huge
in a few months and I wanna prepare for it.

* Table of Contents :toc:
- [[#very-important][VERY IMPORTANT]]
- [[#doxxing-myself][Doxxing Myself]]
- [[#appearance][Appearance]]
  - [[#fonts][Fonts]]
  - [[#colors][Colors]]
  - [[#editing-experience][Editing Experience]]
  - [[#dashboard][Dashboard]]
- [[#better-defaults][Better Defaults]]
  - [[#simple-settings][Simple Settings]]
  - [[#frame-sizing][Frame Sizing]]
  - [[#windows][Windows]]
- [[#langs][Langs]]
  - [[#org][Org]]
- [[#packages][Packages]]
  - [[#corfu][Corfu]]

* VERY IMPORTANT
Probably the only good piece of code I'll write here.

#+begin_src emacs-lisp
;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-
#+end_src

* Doxxing Myself
Here, I publicize my name and email address. Please don't spam me.

#+begin_src emacs-lisp
(setq user-full-name "Daniel Xu"
      user-mail-address "danielxu0307@proton.me")
#+end_src

* Appearance
** Fonts
Berkeley Mono/Inter = best combination and I will die on this hill.

#+begin_src emacs-lisp
(setq doom-font (font-spec :family "BerkeleyMono Nerd Font" :size 14)
      doom-variable-pitch-font (font-spec :family "Inter" :size 14))
#+end_src

** Colors
Doom Vibrant is a lil more vibrant than Doom One. Me likey.

#+begin_src emacs-lisp
(setq doom-theme 'doom-gruvbox)
#+end_src

** Editing Experience
Line numbers are pretty slow all around. The performance boost of disabling them
outweighs the utility of always keeping them on.

#+begin_src emacs-lisp
(setq display-line-numbers-type nil)
#+end_src

Prevents some cases of Emacs flickering.

#+begin_src emacs-lisp
(add-to-list 'default-frame-alist '(inhibit-double-buffering . t))
#+end_src

** Dashboard
Make the dashboard more minimal, removing the menus and adding a nice Emacs
logo.

#+begin_src emacs-lisp
(setq fancy-splash-image (file-name-concat doom-user-dir "splash.png"))
(setq +doom-dashboard-functions '(doom-dashboard-widget-banner))
#+end_src

* Better Defaults
** Simple Settings
#+begin_src emacs-lisp
(setq-default
 delete-by-moving-to-trash t                      ; Delete files to trash
 window-combination-resize t                      ; take new window space from all other windows (not just current)
 x-stretch-cursor t)                              ; Stretch cursor to the glyph width

(setq undo-limit 80000000                         ; Raise undo-limit to 80Mb
      evil-want-fine-undo t                       ; By default while in insert all changes are one big blob. Be more granular
      auto-save-default t                         ; Nobody likes to loose work, I certainly don't
      truncate-string-ellipsis "…"                ; Unicode ellispis are nicer than "...", and also save /precious/ space
      password-cache-expiry nil                   ; I can trust my computers ... can't I?
      ;; scroll-preserve-screen-position 'always     ; Don't have `point' jump around
      scroll-margin 2                             ; It's nice to maintain a little margin
      display-time-default-load-average nil)      ; I don't think I've ever found this useful

(display-time-mode 1)                             ; Enable time in the mode-line
(global-subword-mode 1)                           ; Iterate through CamelCase words
#+end_src

** Frame Sizing
I can easily maximize an Emacs pane with a hotkey.

#+begin_src emacs-lisp
(add-to-list 'default-frame-alist '(height . 24))
(add-to-list 'default-frame-alist '(width . 80))
#+end_src

** Windows
I find it rather handy to be asked which buffer I want to see after splitting
the window. Let’s make that happen.

First, we’ll enter the new window

#+begin_src emacs-lisp
(setq evil-vsplit-window-right t
      evil-split-window-below t)
#+end_src

Then, we’ll pull up a buffer prompt.

#+begin_src emacs-lisp
(defadvice! prompt-for-buffer (&rest _)
  :after '(evil-window-split evil-window-vsplit)
  (consult-buffer))
#+end_src

* Langs
** Org
Set org directory to my synced Documents folder.

#+begin_src emacs-lisp
(setq org-directory "~/Documents/org")
#+end_src

* Packages
** Corfu
I like Corfu, but I don't like being spammed by it.

#+begin_src emacs-lisp
(setq corfu-auto-delay 0.5)
#+end_src
